<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/assets/css/style.css?v=c554c1c0b6cc885cdfbfdb90210029e3628d2861" media="screen" type="text/css">
    <link rel="stylesheet" href="/assets/css/print.css" media="print" type="text/css">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <style>
      a { color: #FF0000; } /* CSS link color */
    </style>

<!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Ecologic Code | EcologicCode.github.io</title>
<meta name="generator" content="Jekyll v3.9.2" />
<meta property="og:title" content="Ecologic Code" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Le site WebAssembly d’EcologicCode" />
<meta property="og:description" content="Le site WebAssembly d’EcologicCode" />
<link rel="canonical" href="https://ecologiccode.github.io/" />
<meta property="og:url" content="https://ecologiccode.github.io/" />
<meta property="og:site_name" content="EcologicCode.github.io" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Ecologic Code" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebSite","description":"Le site WebAssembly d’EcologicCode","headline":"Ecologic Code","name":"EcologicCode.github.io","url":"https://ecologiccode.github.io/"}</script>
<!-- End Jekyll SEO tag -->


    <!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->



<!-- You can set your favicon here -->
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

<!-- end custom head snippets -->

  </head>

  <body>
    <header>
      <div class="inner">
        <a href="https://ecologiccode.github.io/">
          <h1>EcologicCode.github.io</h1>
        </a>
        <h2>Le site WebAssembly d'EcologicCode</h2>
        <font size="6"><p style="color:yellow"><a href="informatique/">Informatique</a> - <a href="Account/">Mon Compte</a> - <a href="Community/">Communauté...</a> - <a href="Tools/">Outils</a></p></font>
          <a href="https://github.com/EcologicCode" class="button"><small>Follow me on</small> GitHub</a>
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix">
        <section id="main-content">
          <h1 id="ecologic-code">Ecologic Code</h1>
<center style="background-color:green">Autre version du site disponible <a href="App/Web/EcologicCodeWebSite.html">ici</a></center>
<p><br /></p>
<link href="https://superatraction.github.io/JQuery/jquery-ui.css" rel="stylesheet" />
<button onclick="location.href='lang.html'">Langs</button><br>
          <a href="informatique/index.html">La partie du site Informatique (et vous y trouverez OpenCreators)
<a href="Web/" target="about:">Outils du site...</a>
<a href="Store_center/">Store Center : Le Store Officiel d'ExologicCode.</a>
          <h1 onclick="location.href=\"Linux/\"">Linux (Plus précisément Ubuntu & Kubuntu Plasma)</h1>
<script type="module" src="/JQuery/js.cookie.min.mjs"></script>

<script type="module">
  import Cookies from '/JQuery/js.cookie.min.mjs'

  Cookies.set('lang', navigator.language, { expires: 365 });
</script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        </section>

        <aside id="sidebar">
          <p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</p>
        </aside>
      </div>
    </div>
  </body>
</html>
